name = "amor-saudefreedback"
main = "src/index.js"
compatibility_date = "2026-07-29"

[assets]
directory = "./site"
binding = "ASSETS"
run_worker_first = ["/api/*"]

name = "amor-saude-feedback"
main = "src/index.js"
compatibility_date = "2026-07-29"

[assets]
directory = "./site"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "amorsaudeexp4-db"
database_id = "d3c0be5c-3170-42e0-9339-ecd1d61974fe"
